Repository sayan404/TaskPulse, pull requests merged in 2024-01, with the labels that each got.

#4 Changed login form container for better usability when in mobile view
  frontend/src/Components/User/LoginSignup.css
Labels: bug, good first issue, JWOC, Easy

#6 UI enhancement
  frontend/src/Components/Home/Home.css
Labels: JWOC, Easy

#8 fix issue of duplicate lines
  frontend/src/Components/Home/Home.jsx
Labels: good first issue, JWOC, Easy

#15 added task page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Components/TaskProfile/TaskProfile.css
  frontend/src/Components/TaskProfile/TaskProfile.jsx
Labels: enhancement, JWOC, Medium

#20 Fix typo & make code look better.
  README.md
  backend/Controllers/TaskController.js
  backend/Controllers/UserController.js
  backend/Database/DataBase.js
  backend/Middleware/Auth.js
  backend/Middleware/CatchAsyncError.js
  backend/Models/TaskModel.js
  backend/Models/UserModel.js
  backend/Utils/ErrorHandler.js
  backend/Utils/JwtToken.js
  backend/server.js
  frontend/dist/index.html
  frontend/index.html
  frontend/src/App.jsx
  frontend/src/Components/Home/Home.css
  frontend/src/Components/Home/Home.jsx
  frontend/src/Components/TaskProfile/TaskProfile.css
  frontend/src/Components/TaskProfile/TaskProfile.jsx
  frontend/src/Components/User/LoginSignup.css
  frontend/src/Components/User/LoginSignup.jsx
  frontend/src/Data/data.js
  frontend/src/Reducer/UserReducer.js
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/store.js
Labels: enhancement, JWOC, Medium

#21 API for get all tasks
  backend/Controllers/TaskController.js
  backend/Routes/TaskRoute.js
Labels: enhancement, JWOC, Medium

#23 [ Backend ] - API for Task Deletion
  backend/Controllers/TaskController.js
  backend/Routes/TaskRoute.js
Labels: enhancement, JWOC, Medium
