Repository sayan404/TaskPulse, pull requests merged in 2024-02, with the labels that each got.

#26 Backend: Enhancing Signup workflow by using Regex.
  backend/Controllers/UserController.js
  backend/Utils/Regex.js
Labels: bug, enhancement, JWOC, Medium

#25 [ Backend ] - Task Details Update Route
  backend/Controllers/TaskController.js
  backend/Routes/TaskRoute.js
Labels: JWOC, Medium

#30 Add Update Password Functionality
  backend/Controllers/UserController.js
  backend/Routes/UserRoute.js
Labels: JWOC, Medium

#32 Add Update User Details Functionality
  backend/Controllers/UserController.js
  backend/Routes/UserRoute.js
Labels: JWOC, Medium

#33 Fixing Issue of Login Route
  backend/Controllers/UserController.js
  frontend/.env
  frontend/src/Action/UserAction.js
  frontend/src/Components/User/LoginSignup.jsx
Labels: JWOC, Medium

#35 insert status felid in task schema
  backend/Models/TaskModel.js
Labels: JWOC, Easy

#39 Added UpdateTakStatus controller
  backend/Controllers/TaskController.js
  backend/Routes/TaskRoute.js
Labels: JWOC, Medium

#41 User notification system complete, notifications objects will be crea…
  backend/Controllers/NotificationController.js
  backend/Controllers/TaskController.js
  backend/Models/NotificationModel.js
  backend/Models/TaskModel.js
  backend/Notifications/NotificationCronJob.js
  backend/Routes/NotificationRoute.js
  backend/app.js
  backend/package-lock.json
  backend/package.json
  backend/server.js
Labels: enhancement, Hard, JWOC

#42 Implementing Refresh Token Mechanism for Enhanced Authentication
  backend/Controllers/UserController.js
  backend/Models/UserModel.js
  backend/Routes/UserRoute.js
  backend/Utils/JwtToken.js
Labels: JWOC, Medium

#45 alert added on register
  frontend/src/Action/UserAction.js
  frontend/src/Components/User/LoginSignup.jsx
Labels: JWOC, Medium

#46 Implement Automatic Sign-in Using Refresh Token
  backend/Controllers/UserController.js
  backend/Models/UserModel.js
  backend/Utils/ErrorHandler.js
  backend/Utils/JwtToken.js
  backend/app.js
  frontend/package.json
  frontend/src/Action/UserAction.js
  frontend/src/Components/Home/Home.css
  frontend/src/Components/Home/Home.jsx
  frontend/src/Constants/UserConstant.js
  frontend/src/Reducer/UserReducer.js
Labels: JWOC, Medium

#48 Improved UI of the Website
  frontend/src/Components/Home/Home.css
  frontend/src/Components/User/LoginSignup.css
  package-lock.json
Labels: JWOC, Easy
